In [64]:
import pandas as pd

dfm1 = pd.read_csv("../data/prices_round_4_day_1.csv", sep=';')
dfm2 = pd.read_csv("../data/prices_round_4_day_2.csv", sep=';')
dfm3 = pd.read_csv("../data/prices_round_4_day_3.csv", sep=';')
df1 = pd.read_csv("../data/observations_round_4_day_1.csv")
df2 = pd.read_csv("../data/observations_round_4_day_2.csv")
df3 = pd.read_csv("../data/observations_round_4_day_3.csv")
df2['timestamp'] += 1_000_000
df3['timestamp'] += 2_000_000
dfm2['timestamp'] += 1_000_000
dfm3['timestamp'] += 2_000_000
dfm_all = pd.concat([dfm1, dfm2, dfm3], ignore_index=True)
df_all = pd.concat([df1, df2, df3], ignore_index=True)



dfm_all = dfm_all[dfm_all['product'] == 'MAGNIFICENT_MACARONS']

In [65]:
dfm_all

,day,timestamp,product,bid_price_1,bid_volume_1,bid_price_2,bid_volume_2,bid_price_3,bid_volume_3,ask_price_1,ask_volume_1,ask_price_2,ask_volume_2,ask_price_3,ask_volume_3,mid_price,profit_and_loss
6,1,0,MAGNIFICENT_MACARONS,624.0,20.0,622.0,12.0,617.0,23.0,631,10,639.0,23.0,644.0,12.0,627.5,0.0
29,1,100,MAGNIFICENT_MACARONS,627.0,14.0,625.0,12.0,620.0,21.0,634,7,642.0,21.0,647.0,12.0,630.5,0.0
41,1,200,MAGNIFICENT_MACARONS,627.0,10.0,625.0,15.0,620.0,21.0,634,5,642.0,21.0,647.0,15.0,630.5,0.0
47,1,300,MAGNIFICENT_MACARONS,629.0,14.0,627.0,14.0,622.0,26.0,636,7,644.0,26.0,649.0,14.0,632.5,0.0
73,1,400,MAGNIFICENT_MACARONS,628.0,18.0,625.0,16.0,620.0,26.0,635,9,643.0,26.0,648.0,16.0,631.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449932,3,2999500,MAGNIFICENT_MACARONS,794.0,12.0,792.0,16.0,786.0,22.0,802,6,811.0,22.0,817.0,16.0,798.0,0.0
449940,3,2999600,MAGNIFICENT_MACARONS,798.0,10.0,796.0,13.0,790.0,29.0,806,5,815.0,29.0,821.0,13.0,802.0,0.0
449967,3,2999700,MAGNIFICENT_MACARONS,801.0,20.0,798.0,16.0,792.0,20.0,809,10,817.0,20.0,823.0,16.0,805.0,0.0
449977,3,2999800,MAGNIFICENT_MACARONS,795.0,14.0,793.0,13.0,787.0,22.0,803,7,812.0,22.0,818.0,13.0,799.0,0.0
449985,3,2999900,MAGNIFICENT_MACARONS,794.0,12.0,791.0,18.0,785.0,23.0,802,6,810.0,23.0,816.0,18.0,798.0,0.0